### ISSUE TITLE
Define ouput view type through user settings file, instead REPL output view is `panel` by deafult, 

### ISSUE THREAD

**Issue by lensgolda** [eerohele/Tutkain#103]
Hi, 
By default output view is created with [ouput=panel](https://github.com/eerohele/Tutkain/blob/6bc7bb94495a7ba4cfdc66c22bd63b32c6b50333/src/core.py#L552) when run TutkainConnectCommand through ST Command Pallette.
And there is no way to set this option with Tutkain user settings file, accept ...well, Tutkain Keybindings like this:
```json
// Connect to a socket server.
    {
        "keys": ["ctrl+c", "ctrl+x"],
        "command": "tutkain_connect",
        "args": {"host": "localhost", "output": "view"}
    },
```
So only when you set something different from `"output": "panel"`, REPL view opens in vertical oriented tab, like normal file view, [here](https://github.com/eerohele/Tutkain/blob/34b1ae9147a28faa9badedf3818f69bbb9e0e4ef/src/repl/views.py#L142-L146) it is.
And this is what i actually want should be. 
Because maybe i'm the only one, who don't like that REPL view opened at the window bottom, and showed horizontally oriented. Ok, maybe i didn't found how to do that another way. The one thing i have found, is that option
```json
// Valid options:
  // - "horizontal"
  // - "vertical"
  "layout": "horizontal",
```
but it's not working for me, no matter where and how i'm trying to configure it.

-- All the Best

**Comment by eerohele** [comment]
Thanks for reporting the issue!

Defining a key binding as above combined 
with **Package Settings** » **Tutkain** » `"layout": "vertical"` definitely should work. I just tested it, and it works on my machine™.

![vertical](https://user-images.githubusercontent.com/31859/201104674-0563666d-6182-4a12-88a0-89f3ca9e41aa.gif)

(Excuse the potato quality.)

I'm not sure why it's not working for you. I'll try to look into it a bit more when I get the time.

**Comment by eerohele** [comment]
Oh, I see, I misunderstood — apologies.

Yeah, Tutkain doesn't let you choose between a panel and a view when connecting via the command palette, because I don't want to force the user to go through too many inputs.

One thing you could do is make your own custom command:

1. In the `User` directory under the Sublime Text `Packages` directory (you can find it via **Preferences** » **Browse Packages…** on macOS), create a file called `MyAwesomeCommands.sublime-commands`.
2. In `MyAwesomeCommands.sublime-commands`, add this content:

    ```json
    {
      "caption": "Tutkain: My Awesome Connect",
      "command": "tutkain_connect",
      "args": {"host": "localhost", "output": "view"}
    },
    ```
3. Save the file.

**Tutkain: My Awesome Connect** should now show up in your command palette.

You can obviously further customize the command (e.g. add a port number if you always connect to the same port).

An additional tip: you can use `.sublime-commands` to add all kinds of useful commands into the Command Palette. For example, [here's my custom command file](https://github.com/eerohele/hukari/blob/main/Hukari.sublime-commands)  (and a bit of [explanation](https://clojurians.slack.com/archives/C030F786GAD/p1661591541134349) if you're in the Clojurians Slack).

**Comment by lensgolda** [comment]
Thank you many times, it suits me perfectly!
