### ISSUE TITLE
Arcadia nrepl freeze on connection

### ISSUE THREAD

**Issue by slifin** [eerohele/Tutkain#31]
Arcadia is a Clojure CLR project that can be used to code unity games

These two projects weren't guaranteed to work together anyway but figured I'd report just in case it's a straight forward thing

https://github.com/arcadia-unity/Arcadia/wiki/REPL

Arcadia advertises a nrepl server on port 3722 when trying to connect to it via Tutkain, sublime locks up, the following logs are displayed (sublime freezes to the point I can't check the console):

<img width="601" alt="Screenshot 2020-10-13 at 22 17 03" src="https://user-images.githubusercontent.com/198857/95917358-071aec00-0da2-11eb-9515-330bcedb5cf5.png">

<img width="1440" alt="Screenshot 2020-10-13 at 22 17 24" src="https://user-images.githubusercontent.com/198857/95917366-0b470980-0da2-11eb-9c05-2acd561cde70.png">

Thank you again for sharing Tutkain it's very cool

**Comment by eerohele** [comment]
Interesthing, thanks for reporting the issue! I'll take a look when I get the chance.

One thing you could try if possible:

1. In Sublime Text, choose **Preferences** » **Package Settings** » **Tutkain** » **Settings**.
1. Set `debug` to `true`.
1. In Sublime Text, choose **View** > **Show Console**.

Then try connecting to the Arcadia nREPL server and check whether there's anything interesting in the console. It might be that ST freezes before it can ever print anything into the console, but it's worth a shot.

**Comment by eerohele** [comment]
Thanks, no need any more. I got to the bottom of the issue. I hope to have a fix out pretty soon.

**Comment by slifin** [comment]
oh cool you beat me to it:
<img width="1440" alt="Screenshot 2020-10-15 at 18 31 30" src="https://user-images.githubusercontent.com/198857/96165645-cee7ea80-0f14-11eb-9e7d-26f49475b41e.png">

<img width="598" alt="Screenshot 2020-10-15 at 18 31 49" src="https://user-images.githubusercontent.com/198857/96165637-cd1e2700-0f14-11eb-92a7-5fc64289237c.png">

**Comment by eerohele** [comment]
This should be fixed in 0.5.7. It'll take a while (maybe a couple of hours or so) to appear in Package Control, but when you get the chance, can you give it a try and let me know whether it works for you? I only gave it a very cursory try.

**Comment by slifin** [comment]
Amazing 
<img width="1135" alt="Screenshot 2020-10-15 at 22 39 06" src="https://user-images.githubusercontent.com/198857/96188816-49296680-0f37-11eb-9de6-f198bce4620a.png">
I need to remember how to use this :D

**Comment by eerohele** [comment]
Looks like it works, then? 👍 

Just a heads up: features like test integration and evaluation result pretty-printing won't work because they rely on features in nREPL 0.8 and newer. Basic stuff should work, though.

I'll close this issue, but if anything else pops up, feel free to comment here or open a new issue.

**Comment by eerohele** [comment]
@slifin: Sorry for the ping, but I just wanted to give you the heads-up since you might be (?) the only person other than me using Tutkain: I'll be pivoting Tutkain from nREPL to Socket REPL.

What I've really wanted all along is to have a fast editor that can connect to a Clojure socket REPL and offer basic editing conveniences like auto-completion, symbol lookup, ParEdit, etc. without any dependencies on the server.

I initially went with nREPL because I couldn't figure out a way to do that well without nREPL. Now that I've come up with a solution that works great (or I think so, at least), and Tutkain is still alpha, I'll be dropping nREPL support because I won't be needing or using it anymore myself. The big plus here is that I believe the end result is a lot better than the nREPL version, and has much more potential. Also, after the pivot, I'll have zero dependencies on both the client and the server, which is nice. It also means I can move much faster in improving auto-completion support etc.

I'm sorry for the disruption. I hope this won't cramp your style too bad. If you need the nREPL version of Tutkain, you can always fork the project, of course.

I'm still interested in supporting Arcadia to some extent, even though I don't use it myself. I believe Arcadia has a socket REPL, too, so I'd like to make sure Tutkain supports that. The bare minimum (eval), at least. I'll look into it once I get everything else sorted out.

**Comment by slifin** [comment]
hey @eerohele 

Thanks for the update, sounds good, at the moment I can't think of any hard dependencies in my projects for nREPL but just in case for me and others is it possible to post the commit hash you'd recommend using for that fork?

**Comment by eerohele** [comment]
Sure, it's 3a87a3ceafaf3731f9febe9c42888f647d79948f. I'll try to remember and add that hash into the docs as well.

**Comment by eerohele** [comment]
v0.7.0 is out now, and I unfortunately didn't have the time to look into Arcadia support yet, but I'd like to restore it if possible. If you still need it, could you open a new issue so that I don't forget?

My thinking is that I'll add a "plain socket REPL" connection type, which would also work for Arcadia. That wouldn't support syntax-highlighted eval results, auto-completion, var metadata lookups, or any of the other bells and whistles, but it would let you eval code, at least.
