### ISSUE TITLE
ShadowCLJS support

### ISSUE THREAD

**Issue by slifin** [eerohele/Tutkain#35]
I've been working on a shadowCLJS node-script project that allows npm packages with code like:

    (ns foo 
      (:require ["iohook" as iohook]))

When trying to REPL into the project for ShadowCLJS the first step is to connect to the nrepl server and then 
execute (shadow/node-repl) to step into the node repl, this works with Cursive Intellji but doesn't appear to work in Tutkain

**Comment by eerohele** [comment]
Thanks for the report.

shadow-cljs oughta work, I think, although I haven't tried with Node.js specifically. I just tried doing `(shadow.cljs.devtools.api/nrepl-select :app)` in one of my projects and it worked OK.

How does "doesn't appear to work" manifest, specifically? Are you using the Tutkain version that's available on Package Control, or a Git clone? I'm just asking because the repo is quite a bit ahead of the released package. If you're not afraid to live on the edge, you could give the Git repo version a go, too.

In any case, I'll give `shadow/node-repl` a try tomorrow.

**Comment by eerohele** [comment]
`(shadow.cljs.devtools.api/node-repl)` also works for me. There are many ways to use shadow-cljs, though, so maybe you're running it differently. In any case, in would be useful to know how exactly it doesn't work.

You could also try enabling debug logging (Preferences > Package Settings > Tutkain > Settings, set `debug` to `true` and restart ST) and see if anything interesting turns up in the ST console.

**Comment by slifin** [comment]
Sorry I should have specified, I think it acted like the shadow namespace didn't exist, I haven't tried `(shadow.cljs.devtools.api/node-repl)` yet

**Comment by eerohele** [comment]
v0.7.0 adds bespoke shadow-cljs support. Start a shadow-cljs watch and use **Tutkain: Connect** » **ClojureScript** to connect to a shadow-cljs socket REPL.
